rework basenode to use exec.d/*/charm-pre-install

diff --git a/hooks/install b/hooks/install
--- a/hooks/install
+++ b/hooks/install
@@ -1,16 +1,17 @@
 #!/bin/bash
 
 set -e
-
-### BASENODE BEGIN ####
-basenode_setup() {
-    juju-log 'basenode_setup: begin'
-    (cd basenode && python setup.py install)
-    /usr/local/bin/basenode_init
-    juju-log 'basenode_setup: end'
-}
-basenode_setup
-### BASENODE END   ####
+if [[ -d exec.d ]]; then
+    shopt -s nullglob
+    for f in exec.d/*/charm-pre-install; do 
+        [[ -x "$f" ]] || continue
+        ${SHELL} -c "$f"|| {
+            ## bail out if anyone fails
+            juju-log -l ERROR "$f: returned exit_status=$? "
+            exit 1
+        }
+    done
+fi
 
 DEBIAN_FRONTEND=noninteractive apt-get -y install -qq memcached
 
